services:
  ros:
    image: ros:noetic
    container_name: k1
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
    environment:
      - color_prompt=yes
      - DISPLAY
      - TERM
      - QT_X11_NO_MITSHM=1
      - DRI_NAME=card1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NV_PRIME_RENDER_OFFLOAD=1
      - GLX_VENDOR_LIBRARY_NAME=nvidia
    tty: true
    stdin_open: true
    devices:
      - /dev/:/dev/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
